"""Execution event codes (Phase-5 spec §39).

Reuses the existing in-process ``EventBus`` (``app.core.events``): the
execution service publishes these type codes with a JSON-safe payload
(the execution result summary).  No duplicate event infrastructure, no
network — receiving layers (logs, control API, future storage) subscribe
to the same bus.
"""

from __future__ import annotations

EXECUTION_REQUESTED = "EXECUTION_REQUESTED"
EXECUTION_CHECKED = "EXECUTION_CHECKED"
EXECUTION_SENT = "EXECUTION_SENT"
EXECUTION_SIMULATED = "EXECUTION_SIMULATED"
EXECUTION_FILLED = "EXECUTION_FILLED"
EXECUTION_REJECTED = "EXECUTION_REJECTED"
EXECUTION_FAILED = "EXECUTION_FAILED"
EXECUTION_UNKNOWN = "EXECUTION_UNKNOWN"

RECONCILIATION_MATCHED = "RECONCILIATION_MATCHED"
RECONCILIATION_MISMATCH = "RECONCILIATION_MISMATCH"

#: Control-plane operations (Phase 5E) — same bus, same audit trail.
CONTROL_STARTED = "CONTROL_STARTED"
CONTROL_STOPPED = "CONTROL_STOPPED"
CONTROL_DRY_RUN_FORCED = "CONTROL_DRY_RUN_FORCED"
CONTROL_EMERGENCY_STOP = "CONTROL_EMERGENCY_STOP"
CONTROL_KILL_SWITCH_RESET = "CONTROL_KILL_SWITCH_RESET"
CONTROL_RECONCILIATION_ACKNOWLEDGED = "CONTROL_RECONCILIATION_ACKNOWLEDGED"

EXECUTION_COMPONENT = "execution"
RECONCILIATION_COMPONENT = "reconciliation"
CONTROL_COMPONENT = "control"

__all__ = [
    "CONTROL_COMPONENT",
    "CONTROL_DRY_RUN_FORCED",
    "CONTROL_EMERGENCY_STOP",
    "CONTROL_KILL_SWITCH_RESET",
    "CONTROL_RECONCILIATION_ACKNOWLEDGED",
    "CONTROL_STARTED",
    "CONTROL_STOPPED",
    "EXECUTION_CHECKED",
    "EXECUTION_COMPONENT",
    "EXECUTION_FAILED",
    "EXECUTION_FILLED",
    "EXECUTION_REJECTED",
    "EXECUTION_REQUESTED",
    "EXECUTION_SENT",
    "EXECUTION_SIMULATED",
    "EXECUTION_UNKNOWN",
    "RECONCILIATION_COMPONENT",
    "RECONCILIATION_MATCHED",
    "RECONCILIATION_MISMATCH",
]
